"""nullable ext

Revision ID: cf8a975d1fd9
Revises: 757ebb2d489b
Create Date: 2024-06-29 17:54:42.720260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf8a975d1fd9'
down_revision: Union[str, None] = '757ebb2d489b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'ext',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'ext',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
